Gocardless\EnterpriseBundle\Entity\Mandate:
    type: entity
    table: gocardless_mandate
    id:
        id:
            type: string
            length: 20
    fields:
        reference:
            type: string
        scheme:
            type: string
        status:
            type: string
        pdfPath:
            type: string
        created_at:
            type: datetime
    manyToOne:
        customerBankAccount:
            targetEntity: CustomerBankAccount
            inversedBy: mandates
            cascade: ["persist"]
