parameters:
#    gocardless_enterprise.example.class: Gocardless\EnterpriseBundle\Example

services:
#    gocardless_enterprise.example:
#        class: %gocardless_enterprise.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    gocardless_enterprise.client:
        class: GoCardless\Enterprise\Client
        arguments: [@guzzle.client, %gocardless_enterprise%]
