language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1.21 # see https://github.com/liamja/cex/commit/bb5906b373dca1f5163a265925f57bddc446b9cd
  - 7.2
  - nightly
  
env:
  - DEPENDENCIES=beta
  - DEPENDENCIES=low
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.2.*
  - SYMFONY_VERSION=3.3.*
  - SYMFONY_VERSION=3.4.*
  - SYMFONY_VERSION=4.0.*
  - SYMFONY_VERSION=4.1.*
  - SYMFONY_VERSION=dev-master

matrix:
  exclude:
    - php: 5.5
      env: SYMFONY_VERSION=4.0.*
    - php: 5.5
      env: SYMFONY_VERSION=4.1.*
    - php: 5.5
      env: SYMFONY_VERSION=dev-master
    - php: 5.6
      env: SYMFONY_VERSION=4.0.*
    - php: 5.6
      env: SYMFONY_VERSION=4.1.*
    - php: 5.6
      env: SYMFONY_VERSION=dev-master
    - php: 7.0
      env: SYMFONY_VERSION=4.0.*
    - php: 7.0
      env: SYMFONY_VERSION=4.1.*
    - php: 7.0
      env: SYMFONY_VERSION=dev-master
  allow_failures:
    - php: nightly
    - env: DEPENDENCIES=beta
    - env: DEPENDENCIES=low
    - env: SYMFONY_VERSION=dev-master

before_install:
  - composer self-update
  # Set composer minimum-stability configuration filter to beta versions
  - if [ "$DEPENDENCIES" = "beta" ]; then perl -pi -e 's/^}$/,"minimum-stability":"beta"}/' composer.json; fi;
  # Force Symfony version
  - if [ "$SYMFONY_VERSION" != "" ]; then composer --no-update require symfony/symfony:${SYMFONY_VERSION}; fi;
  # Disable xdebug, there is no use of it being enabled
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"
  # Prevent Travis throwing an out of memory error
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  # Test if we have a token for github as the project easily hits the 60 rph limit
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;

install:
  - if [ "$DEPENDENCIES" = "low" ]; then composer --prefer-lowest --prefer-stable update; else composer update; fi;

script:
  - composer validate-files
  - if [ $(phpenv version-name) != "5.5" ]; then composer check-code-style; fi;
  - composer check-security
