language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly
  
env:
  - DEPENDENCIES=beta
  - DEPENDENCIES=low
  - SYMFONY_VERSION=2.7.* # LTS (until 05/2019)
  - SYMFONY_VERSION=2.8.* # LTS (until 11/2019)
  - SYMFONY_VERSION=3.2.* # (until 01/2018)
  - SYMFONY_VERSION=3.3.* # (until 07/2018)
  - SYMFONY_VERSION=3.4.* # LTS (until 11/2021)
  - SYMFONY_VERSION=4.0.* # (until 01/2019)
  - SYMFONY_VERSION=dev-master

matrix:
  exclude:
    - php: 5.6
      env: SYMFONY_VERSION=4.0.* # requires PHP ^7.1.3
    - php: 5.6
      env: SYMFONY_VERSION=dev-master # requires PHP ^7.1.3
    - php: 7.0
      env: SYMFONY_VERSION=4.0.* # requires PHP ^7.1.3
    - php: 7.0
      env: SYMFONY_VERSION=dev-master # requires PHP ^7.1.3
  allow_failures:
    - php: nightly
    - env: DEPENDENCIES=beta
    - env: DEPENDENCIES=low
    - env: SYMFONY_VERSION=dev-master

before_install:
  - composer self-update
  # Set composer minimum-stability configuration filter to beta versions
  - if [ "$DEPENDENCIES" = "beta" ]; then perl -pi -e 's/^}$/,"minimum-stability":"beta"}/' composer.json; fi;
  # Force Symfony version
  - if [ "$SYMFONY_VERSION" != "" ]; then composer --no-update require symfony/symfony:${SYMFONY_VERSION}; fi;
  # Disable xdebug, there is no use of it being enabled
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"
  # Prevent Travis throwing an out of memory error
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  # Test if we have a token for github as the project easily hits the 60 rph limit
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;

install:
  - if [ "$DEPENDENCIES" = "no" ]; then composer update; fi;
  - if [ "$DEPENDENCIES" = "low" ]; then composer --prefer-lowest --prefer-stable update; fi;

script:
  - composer validate-files
  - composer code-style
