language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - 7.1.21 # see https://github.com/liamja/cex/commit/bb5906b373dca1f5163a265925f57bddc446b9cd
  - 7.2
  - nightly

env:
  global:
    - LATEST_PHP_VERSION="7.2"
    - MAINTAINED_SYMFONY_VERSIONS="2.8.*|3.4.*|4.0.*|4.1.*|4.2.*"
  matrix:
    - SYMFONY_VERSION="2.7.*"
    - SYMFONY_VERSION="2.8.*"
    - SYMFONY_VERSION="3.0.*"
    - SYMFONY_VERSION="3.1.*"
    - SYMFONY_VERSION="3.2.*"
    - SYMFONY_VERSION="3.3.*"
    - SYMFONY_VERSION="3.4.*"
    - SYMFONY_VERSION="4.0.*"
    - SYMFONY_VERSION="4.1.*"
    - SYMFONY_VERSION="4.2.*"
    - SYMFONY_VERSION="dev-master"
    - DEPENDENCIES="beta"
    - DEPENDENCIES="low"
    - DEPENDENCIES="stable"

matrix:
  fast_finish: true
  exclude:
    - php: 5.6
      env: SYMFONY_VERSION="4.0.*"
    - php: 5.6
      env: SYMFONY_VERSION="4.1.*"
    - php: 5.6
      env: SYMFONY_VERSION="4.2.*"
    - php: 5.6
      env: SYMFONY_VERSION="dev-master"
    - php: 7.0
      env: SYMFONY_VERSION="4.0.*"
    - php: 7.0
      env: SYMFONY_VERSION="4.1.*"
    - php: 7.0
      env: SYMFONY_VERSION="4.2.*"
    - php: 7.0
      env: SYMFONY_VERSION="dev-master"
  allow_failures:
    - php: nightly
    - env: DEPENDENCIES="beta"
    - env: DEPENDENCIES="low"
    - env: SYMFONY_VERSION="dev-master"

before_install:
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - if [ -n "$GH_TOKEN" ]; then
      composer config github-oauth.github.com ${GH_TOKEN};
    fi;
  - mkdir -p build/logs

install:
  - if [ "$DEPENDENCIES" = "beta" ]; then
      composer config minimum-stability beta;
      composer update -n --prefer-dist;
    elif [ "$DEPENDENCIES" = "low" ]; then
      composer update -n --prefer-dist --prefer-lowest;
    elif [ "$SYMFONY_VERSION" != "" ]; then
      composer remove symfony/symfony --dev &&
      composer require symfony/symfony:"${SYMFONY_VERSION}" --dev --no-update;
    else
      composer update -n --prefer-dist;
    fi;

script:
  - if [ "$(phpenv version-name)" != "$LATEST_PHP_VERSION" ]; then
      echo "File validation is skipped for older PHP versions";
    else
      composer validate-files;
    fi;
  - if [ "$(phpenv version-name)" != "$LATEST_PHP_VERSION" ]; then
    echo "Code style check is skipped for older PHP versions";
    else
      composer check-code-style;
    fi;
  - if [ "$(phpenv version-name)" != "$LATEST_PHP_VERSION" ]; then
      echo "Security check is skipped for older PHP versions";
    else
      composer check-security;
    fi;
