language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.5
      dist: precise
      env: SYMFONY_VERSION=2.8.*
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*
    - php: 5.6
      env: SYMFONY_VERSION=^3.0
    - php: 7.0
      env: SYMFONY_VERSION=2.8.*
    - php: 7.0
      env: SYMFONY_VERSION=^3.0
    - php: 7.0
      env: DEPENDENCIES=beta
    - php: 7.1
      env: SYMFONY_VERSION=^3.0
    - php: 7.1
      env: DEPENDENCIES=beta
    - php: 7.2
      env: SYMFONY_VERSION=^3.0
    - php: 7.2
      env: DEPENDENCIES=beta
    - php: nightly
      env: SYMFONY_VERSION=^3.0
    - php: nightly
      env: DEPENDENCIES=beta
  allow_failures:
    - php: nightly

env:
  global:
    - deps=no

before_install:
  - composer self-update
  # Prevent Travis throwing an out of memory error on PHP 5.5
  - if [ $(phpenv version-name) == 5.5 ]; then echo "memory_limit=-1" >> ~/.phpenv/versions/5.5/etc/conf.d/travis.ini; fi;
  # Prevent Travis throwing an out of memory error on PHP 5.6
  - if [ $(phpenv version-name) == 5.6 ]; then echo "memory_limit=-1" >> ~/.phpenv/versions/5.6/etc/conf.d/travis.ini; fi;
  # Disable xdebug for improved performance; Unstable PHP versions, like nightly, don't have xdebug enabled
  - if [ $(phpenv version-name) != "nightly" ]; then phpenv config-rm xdebug.ini; fi;
  # Set composer minimum-stability configuration filter to beta versions
  - if [ "$DEPENDENCIES" = "beta" ]; then perl -pi -e 's/^}$/,"minimum-stability":"beta"}/' composer.json; fi;
  # Test if we have a token for github as the project easily hits the 60 rph limit
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;

install:
  - if [ "$deps" = "no" ]; then composer update; fi;
  - if [ "$deps" = "low" ]; then composer --prefer-lowest --prefer-stable update; fi;

script:
  - vendor/jakub-onderka/php-parallel-lint/parallel-lint --exclude vendor .
