services:
    Lendable\GoCardlessEnterprise\Client:
        public: false
        arguments:
            $client: '@gocardless_enterprise.guzzle_client'
            $config: '%gocardless_enterprise%'

    gocardless_enterprise.guzzle_client:
        public: false
        class: GuzzleHttp\Client

    gocardless_enterprise.client:
        public: true
        alias: Lendable\GoCardlessEnterprise\Client
